### ISSUE TITLE
Implement Auto Labeling for Issues

### ISSUE THREAD

**Issue by ygowthamr** [multiverseweb/Dataverse#202]
# Title:  
Implement Auto Labeling for Issues

## Description:  
This feature aims to automate the process of assigning labels to issues when they are created or edited. The following labels will be automatically added:

- **gssoc-extd**: Marks the issue as part of GSSOC-extended contributions.  
- **hacktoberfest**: Marks it as eligible for Hacktoberfest.  
- **level?**: A placeholder label indicating the level, which will remain until the project admin assigns the appropriate level during the Pull Request (PR) review.

## Tasks:  
1. Create a **GitHub Action** that listens to issue events (`opened`, `edited`).  
2. Automatically assign the following labels:
   - `gssoc-extd`
   - `hacktoberfest`
   - `level?`  

3. Ensure the placeholder label `level?` remains on the issue until the project admin assigns the final level during the PR stage.  
4. Test the automation by creating and editing issues.

## Acceptance Criteria:  
- [ ] Labels are added to issues automatically upon creation or editing.  
- [ ] Placeholder label `level?` is correctly assigned to issues.  
- [ ] Final level is assigned by the project admin during PR review.  

@multiverseweb
Pls assign me this issue and give me level3,hacktoberfest-accepted and gssoc-extd

**Comment by multiverseweb** [comment]
Hello @ygowthamr, it seems to be wonder contribution, but this will be chaotic as some contributors open irrelevant issues and if they will see `gssoc-extd` and `hacktoberfest` labels applied, they will start working on it and send the corresponding PR.
Then it will be difficult to close the PRs and issues without merging them.

But I will need this mechanism in future, so can you add `Review Queued` label automatically?
Also, if its possible to set the color of label too then set it to `#ffae00`.

**Comment by ygowthamr** [comment]
@multiverseweb 

Basically there will be three labels created when some one creates issue right?

**Comment by multiverseweb** [comment]
@ygowthamr there is no mandatory count of how many labels should be assigned to any created PR. But for an issue or PR to be accepted for GSSoC and Hacktoberfest, there should be atleast these three labels: `gssoc-extd`, `hacktoberfest-accepted` and relevant `levelX`.

I want these labels to be assigned by me, not automatically in order to avoid unnecessary issues.
Did you get your answer?

**Comment by ygowthamr** [comment]
Yeah
